name: Update Submodules

on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  update-submodules:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update Submodules Recursively
        run: |
          echo "Updating submodules recursively..."
          git submodule update --init --recursive
          git submodule update --recursive --remote
          echo "Submodule status after update:"
          git submodule status

      - name: Configure Git User
        run: |
          echo "Configuring git user..."
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "tilbot"

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Checking for changes..."
          if ! git diff --quiet; then
            echo "Changes detected. Committing and pushing..."
            git commit --all --message "Update submodules"
            git push https://viseshrp:${PAT}@github.com/viseshrp/todayilearned.git HEAD:main
          else
            echo "No changes detected. Skipping push."
          fi
